animecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))

]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('animes/', views.animes_index, name='index'),
  path('animes/<int:anime_id>/', views.animes_detail, name='detail'),
  # path('anime/', AnimeList.as_view(), name='animes_index'),
# new route used to show a form and create an anime
  path('animes/create/', views.AnimeCreate.as_view(), name='animes_create'),

  path('animes/<int:pk>/update/', views.AnimeUpdate.as_view(), name='animes_update'),
  path('animes/<int:pk>/delete/', views.AnimeDelete.as_view(), name='animes_delete'),
  path('animes/<int:anime_id>/add_watching/', views.add_watching, name='add_watching'),
  path('animes/<int:anime_id>/add_photo/', views.add_photo, name='add_photo'),
  path('animes/<int:anime_id>/assoc_va/<int:va_id>/', views.assoc_va, name='assoc_va'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date


SEEN = (
    ('M', 'Morning'),
    ('A', 'Afternoon'),
    ('N', 'Night')
)

class Va(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
     return reverse('vas_detail', kwargs={'pk': self.id})

# Create your models here.
class Anime(models.Model):
    title = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    seasons = models.IntegerField()
    vas = models.ManyToManyField(Va)

    # new code below
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'anime_id': self.id})

class Photo(models.Model):
    url = models.CharField(max_length=200)
    anime = models.ForeignKey(Anime, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for anime_id: {self.anime_id} @{self.url}"

class Watching(models.Model):
      date = models.DateField()
      seen = models.CharField(
          max_length=1, 
          choices=SEEN, 
          default=SEEN[0][0]
          )

      anime = models.ForeignKey(Anime, on_delete=models.CASCADE)

      def __str__(self):
        # Nice method for obtaining the friendly value of a Field.choice
        return f"{self.get_seen_display()} on {self.date}"

      class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Watching

class WatchingForm(ModelForm):
  class Meta:
    model = Watching
    fields = ['date', 'seen']

main_app/views.py
from django.shortcuts import render, redirect

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

from django.http import HttpResponse
import uuid
import boto3
from .models import Anime, Va, Photo
from .forms import WatchingForm

S3_BASE_URL = 'https://s3.us-west-2.amazonaws.com/'
BUCKET = 'simanutui'

def add_photo(request, anime_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            # we can assign to cat_id or cat (if you have a cat object)
            Photo.objects.create(url=url, anime_id=anime_id)
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', anime_id=anime_id)

class AnimeCreate(CreateView):
    model = Anime
    # fields = ['title', 'genre', 'description', 'seasons']
    fields = '__all__'
    # template_name = 'animes/index.html'

class AnimeUpdate(UpdateView):
      model = Anime
  # Let's disallow the renaming of a cat by excluding the name field!
      fields = '__all__'

class AnimeDelete(DeleteView):
  model = Anime
  success_url = '/animes/'

# animes = [
#     Anime('Haikyuu', 'Sports', 'Volleyball Anime', 4),
#     Anime('Jujutsu Kaisen', 'Supernatural/Action', 'Shounen Anime about Curses and Jujustsu Sorcerers', 1),
#     Anime('Black Clover', 'Magical/Action', 'Who will be the Wizard King', 1),
#     Anime('Attack On Titan', 'Science Fiction/Action', 'Humanity is on the brink of extinction', 4),

# ]

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def animes_index(request):
    animes = Anime.objects.all()
    return render(request, 'animes/index.html', { 'animes': animes })

def animes_detail(request, anime_id):
    anime = Anime.objects.get(id=anime_id)
    vas_anime_doesnt_have = Va.objects.exclude(id__in = anime.vas.all().values_list('id'))
    watching_form = WatchingForm()
    return render(request, 'animes/detail.html', { 'anime': anime, 'watching_form': watching_form, 'vas': vas_anime_doesnt_have})

def add_watching(request, anime_id):
  form = WatchingForm(request.POST)
  if form.is_valid():
      new_watching = form.save(commit=False)
      new_watching.anime_id = anime_id
      new_watching.save()
  return redirect('detail', anime_id=anime_id)

def assoc_va(request, anime_id, va_id):
    Anime.objects.get(id=anime_id).vas.add(va_id)
    return redirect('detail', anime_id=anime_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
<div class="container red white-text">
    <h1 class="center white-text">About the Anime Collector</h1>
    <hr />
    <p>Fear the Anime Collector!</p>
    <footer>All Rights Reserved, &copy; 2022 Organ Collector</footer>
</div>
{% endblock %}

main_app/templates/animes/detail.html
{% extends 'base.html' %}
{% block content %}

<div class="card">
  <h1><span class="red-text darken-3">Anime</span> Details</h1>


  <div class="card-content">
    <span class="card-title">{{ anime.name }}</span>
    <p>Title: {{ anime.title }}</p>
    <p>Genre: {{ anime.genre }}</p>
    <p>Description: {{ anime.description }}</p>
    {% if anime.seasons == 0 %}
    <p>Seasons: {{ anime.seasons }}
      {% else %}
    <p>Anime: Ongoing</p>
    {% endif %}
  </div>
  <div class="card-action red darken-3">
    <a href="{% url 'animes_update' anime.id %}">Edit</a>
    <a href="{% url 'animes_delete' anime.id %}">Destroy</a>
  </div>
  {% for photo in anime.photo_set.all %}
  <img class="responsive-img card-panel" src="{{photo.url}}">
  {% empty %}
  <div class="card-panel red-text center-align">No Photos Uploaded</div>
  {% endfor %}
  <form action="{% url 'add_photo' anime.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
    {% csrf_token %}
    <input type="file" name="photo-file">
    <br><br>
    <input type="submit" class="btn red darken-3" value="Upload Photo">
  </form>
  <div class="col s6">
    <div class="card white">
      <form action="{% url 'add_watching' anime.id %}" method="post">
        {% csrf_token %}
        {{ watching_form.as_p }}
        <input type="submit" class="btn red darken-3" value="Add Viewing">
      </form>
    </div>
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Seen</th>
        </tr>
      </thead>
      <tbody>
        {% for watching in anime.watching_set.all %}
        <tr>
          <td>{{watching.date}}</td>
          <td>{{watching.get_seen_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="container white">
  <div class="card white">
    <div class="row">
      <div class="col s6">
        <h3>{{ anime.title }}'s Voice Actors</h3>
        {% if anime.va.count %}
        {% for va in anime.va.all %}
        <div class="card white">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ va.color }}">{{ va.color }}</span> {{ va.title }}
            </span>
          </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>No VA's :(</h5>
        {% endif %}
      </div>
    </div>
  </div>
</div>
<div class="col s6">
  <h3>All VA's</h3>
  {% if vas.count %}
  {% for va in vas.all %}
  <div class="card">
    <div class="card-content">
      <span class="card-title">
        <span style="color: {{ va.color }}">{{ va.color }}</span> {{ va.name }}
      </span>
    </div>

    <div class="card-action">
      <form action="{% url 'assoc_va' anime.id va.id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn red darken-3">Add</button>
      </form>
    </div>
  </div>
  {% endfor %}
  {% else %}
  <h5>{{anime.title}} Already Has All VA's Available</h5>
  {% endif %}
</div>
<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
  const selectEl = document.getElementById('id_seen');
  M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/animes/index.html
{% extends 'base.html' %}
{% block content %}

<h1 class="anime-list">Anime List</h1>

{% for anime in animes %}
<div class="card black">
    <!-- <a href="/animes/{{ anime.id }}"> -->
    <a href="{% url 'detail' anime.id %}">
        <div class="card-content white-text">
            <span class="card-title">{{ anime.name }}</span>
            <p>Title: {{ anime.title }}</p>
            <p>Description: {{ anime.genre }}</p>
            {% if anime.seasons == 0 %}
            <p>Seasons: {{ anime.seasons }}</p>
            {% else %}
            <p>Seasons: Ongoing</p>
            {% endif %}
        </div>
    </a>
</div>
{% endfor %}




{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Anime Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper black">
        <ul>
          <li><a href="/" class="center brand-logo">&nbsp;&nbsp;Anime Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'animes_create' %}">Add an Anime</a></li>
          <li><a href="{% url 'index' %}">View All My Anime</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer black">
    <div class="right">All Rights Reserved, &copy; 2021 Wife Collector &nbsp;</div>
  </footer>
</body>

</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="center card-panel red darken-2">
    <h1>Home</h1>
</div>
{% endblock %}

main_app/templates/main_app/anime_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container grey lighten-3">
    <h1>Destroy <span class="red-text darken-3">Anime</span></h1>

    <h4>Are you sure you want to destroy <span class="red-text darken-3">{{ object.title }}</span>?</h4>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes - Destroy!" class="btn red darken-3 pulse">
        <a href="{% url 'detail' anime.id %}"><span class="red-text darken-3">Cancel</span></a>
    </form>
</div>
{% endblock %}

main_app/templates/main_app/anime_form.html
{% extends 'base.html' %}

{% block content %}
<div class="card grey lighten-3">
  {% if object %}
  <h1>Edit <span class="red-text darken-3">{{object.title}}</span></h1>
  {% else %}
  <h1>Add <span class="red-text darken-3">Anime</span></h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn red darken-3">
  </form>
</div>
{% endblock %}